#!/usr/bin/env bash

# Get language
get_lang() {
	lang=$(hyprctl devices -j | jq -r '.keyboards[] | select(.name == "usb-keychron-k2-usb-device") | .active_keymap' | cut -c 1-2 | tr 'A-Z' 'a-z')
	case $lang in
		en)
			lang="English"
			;;
		mo)
			lang="Монгол"
			;;
	esac
	echo $lang
}

# Notify
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "🌐 $(get_lang)"
